### ISSUE TITLE
Ambient Occlusion node not working

### ISSUE THREAD

**Issue by mark3603** [PedroPLopes1/SSRT#3]
Hi, I installed your SSRT version of Blender a while ago, and I recently encountered a problem, or a bug. the Ambient Occlusion node in the Shader Editor does not work, it makes the object, to which the node was set, completely purple. is there any solution?

**Comment by PedroPLopes1** [comment]
I apologize for the delay in responding; I've been occupied.

Thank you for reporting this issue. I tried to replicate the problem you described, but I was unable to reproduce the error where the Ambient Occlusion node turns the object completely purple.

To help me better understand and assist you, could you please send a screenshot showing the node setup in the Shader Editor? Additionally, it would be helpful to know which exact version of Blender you're using.

Thank you for your cooperation!

**Comment by mark3603** [comment]
> I apologize for the delay in responding; I've been occupied.
> 
> Thank you for reporting this issue. I tried to replicate the problem you described, but I was unable to reproduce the error where the Ambient Occlusion node turns the object completely purple.
> 
> To help me better understand and assist you, could you please send a screenshot showing the node setup in the Shader Editor? Additionally, it would be helpful to know which exact version of Blender you're using.
> 
> Thank you for your cooperation!

Sure! i'm using the 0.8 version
![ao  issue](https://github.com/user-attachments/assets/901984a5-bab7-4832-88d3-7ee006652be9)

**Comment by PedroPLopes1** [comment]
Thank you for providing the screenshot. It appears that you're actually using SSGI (Screen Space Global Illumination) rather than my SSRT (Screen Space Ray Tracing) shader. The issue you're experiencing is likely related to the SSGI implementation.

My SSRT shader doesn't modify the Ambient Occlusion node behavior in the way you've described. If you'd like to try the SSRT version to see if it resolves your issue, you can find it in my repository.

Could you confirm which exact shader or modification you're using? This will help me pinpoint the source of the problem more accurately.
